# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 16 Oct 2020 09:06:32 +0000
*               @ALL          1
*               @user         8
