# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Fri, 16 Oct 2020 09:06:32 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

jihadul4kbar:$2y$10$DpNS5qQTm82JgSCkPYyyYed4JT3QNHz2V4IC2uZPhIBp1KVmsBcEC:Jihadul Akbar:jihadul4kbar@gmail.com:admin,user
